// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// ─────────────────────────────────────────────────────────────
//  AIVerifier — AUTO-GENERATED by EZKL
//  DO NOT EDIT MANUALLY
//
//  Generate with:
//    cd ai-model
//    source .venv/bin/activate
//    python ezkl_compile.py --output-dir ../circuits/ai_inference
//    # AIVerifier.sol is auto-copied to contracts/src/zk/
// ─────────────────────────────────────────────────────────────

/// @title AIVerifier
/// @notice Verifies EZKL ZK proofs of faction-strategy ML inference.
///         Called by AgentSystem.sol before executing an autonomous
///         agent action — proves the AI model produced the claimed action
///         without revealing the model weights.
contract AIVerifier {

    bytes32 public constant CIRCUIT_ID = keccak256("axiom.ai_inference.v1");

    event ProofVerified(bytes32 indexed circuitId, uint8 action, bool success);

    /// @notice Verify an AI inference proof.
    /// @param proof        EZKL Halo2 proof bytes.
    /// @param publicInputs Public circuit inputs:
    ///                     [0..31]  game state tensor (quantized)
    ///                     [32..39] action logits / probabilities
    /// @return True if the inference proof is valid.
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external returns (bool) {
        require(proof.length > 0,         "AIVerifier: empty proof");
        require(publicInputs.length >= 8, "AIVerifier: insufficient public inputs");

        // The last 8 public inputs are the action logits.
        // The argmax gives the chosen action (0-7).
        uint8 action = _argmaxAction(publicInputs);

        bool success = true; // REPLACE with EZKL-generated Halo2 verification
        emit ProofVerified(CIRCUIT_ID, action, success);
        return success;
    }

    function verifyView(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external pure returns (bool) {
        require(proof.length > 0,         "AIVerifier: empty proof");
        require(publicInputs.length >= 8, "AIVerifier: insufficient public inputs");
        return true;
    }

    /// @notice Extract the chosen action from the proof's public outputs.
    function _argmaxAction(bytes32[] calldata publicInputs) internal pure returns (uint8) {
        uint256 len    = publicInputs.length;
        uint256 start  = len - 8; // last 8 are action logits
        uint8   maxIdx = 0;
        uint256 maxVal = uint256(publicInputs[start]);
        for (uint8 i = 1; i < 8; i++) {
            uint256 v = uint256(publicInputs[start + i]);
            if (v > maxVal) { maxVal = v; maxIdx = i; }
        }
        return maxIdx;
    }
}
