// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// ─────────────────────────────────────────────────────────────
//  FogVerifier — AUTO-GENERATED by Nargo
//  DO NOT EDIT MANUALLY
//
//  Generate with:
//    cd circuits/fog_of_war
//    nargo codegen-verifier
//    cp contract/plonk_vk.sol ../../contracts/src/zk/FogVerifier.sol
//
//  This placeholder allows the project to compile while the
//  real verifier is being generated. Replace before deployment.
// ─────────────────────────────────────────────────────────────

/// @title FogVerifier
/// @notice Verifies Noir UltraPlonk proofs for fog-of-war movement.
///         Called by MoveSystem.sol before updating tile commitments.
contract FogVerifier {

    // ── Placeholder implementation ─────────────────────────────
    // The real verifier is generated by `nargo codegen-verifier`
    // and contains the actual UltraPlonk verification logic.

    bytes32 public constant CIRCUIT_ID =
        keccak256("axiom.fog_of_war.v1");

    event ProofVerified(bytes32 indexed circuitId, bool success);

    /// @notice Verify a fog-of-war movement proof.
    /// @param proof        Serialised UltraPlonk proof bytes.
    /// @param publicInputs Public circuit inputs:
    ///                     [0] fromCommitment
    ///                     [1] toCommitment
    ///                     [2] movementRange
    ///                     [3] nonce
    ///                     [4] season
    /// @return True if the proof is valid.
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external returns (bool) {
        // ── PLACEHOLDER ────────────────────────────────────────
        // In development: always returns true so the system can
        // be tested end-to-end before the real verifier is ready.
        //
        // In production: replaced by nargo codegen-verifier output
        // which contains full UltraPlonk verification.
        // ──────────────────────────────────────────────────────
        require(proof.length > 0,        "FogVerifier: empty proof");
        require(publicInputs.length == 5, "FogVerifier: wrong input count");

        bool success = true; // REPLACE with real verification
        emit ProofVerified(CIRCUIT_ID, success);
        return success;
    }

    /// @notice Static view version for gas estimation.
    function verifyView(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool) {
        require(proof.length > 0,         "FogVerifier: empty proof");
        require(publicInputs.length == 5, "FogVerifier: wrong input count");
        return true; // REPLACE with real verification
    }
}
