// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// ─────────────────────────────────────────────────────────────
//  TerritoryVerifier — AUTO-GENERATED by Nargo
//  DO NOT EDIT MANUALLY
//
//  Generate with:
//    cd circuits/territory_claim
//    nargo codegen-verifier
//    cp contract/plonk_vk.sol ../../contracts/src/zk/TerritoryVerifier.sol
// ─────────────────────────────────────────────────────────────

/// @title TerritoryVerifier
/// @notice Verifies Noir UltraPlonk proofs for territory claims.
///         Called by ClaimSystem.sol before recording a new tile.
contract TerritoryVerifier {

    bytes32 public constant CIRCUIT_ID = keccak256("axiom.territory_claim.v1");

    event ProofVerified(bytes32 indexed circuitId, bool success);

    /// @notice Verify a territory claim proof.
    /// @param proof        Serialised UltraPlonk proof bytes.
    /// @param publicInputs Public circuit inputs:
    ///                     [0] claimCommitment
    ///                     [1] anchorCommitment
    ///                     [2] civIdHash
    ///                     [3] civId
    ///                     [4] season
    ///                     [5] nonce
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external returns (bool) {
        require(proof.length > 0,         "TerritoryVerifier: empty proof");
        require(publicInputs.length == 6, "TerritoryVerifier: wrong input count");

        bool success = true; // REPLACE with nargo-generated verification
        emit ProofVerified(CIRCUIT_ID, success);
        return success;
    }

    function verifyView(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool) {
        require(proof.length > 0,         "TerritoryVerifier: empty proof");
        require(publicInputs.length == 6, "TerritoryVerifier: wrong input count");
        return true;
    }
}
